# global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['host.docker.internal:9100']
  - job_name: 'alert_manager'
    static_configs:
    - targets: ['host.docker.internal:9093']
  - job_name: 'yourservice'
    static_configs:
    - targets: ['host.docker.internal:8089']

